# Generated by Django 4.1.7 on 2023-04-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
                ('achternaam', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sessie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inzicht', models.IntegerField()),
                ('kennis', models.IntegerField()),
                ('werkhouding', models.IntegerField()),
                ('extra', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('begeleider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.employer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.student')),
            ],
        ),
    ]
