# Generated by Django 4.1.7 on 2023-04-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Leerling',
        ),
        migrations.RenameField(
            model_name='sessie',
            old_name='student',
            new_name='Leerling',
        ),
    ]
