# Generated by Django 4.1.7 on 2023-04-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_school_sessie_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grootte',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='naam',
            field=models.CharField(default=100, max_length=30),
            preserve_default=False,
        ),
    ]
