# Generated by Django 4.1.7 on 2023-04-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_leerling_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessie',
            name='school',
        ),
    ]
