# Generated by Django 4.1.7 on 2023-04-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_sessie_inzicht_alter_sessie_kennis_and_more'),
    ]

    operations = [
    ]
