# Generated by Django 4.1.7 on 2023-04-19 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0008_auto_20230418_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='begeleider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
