# Generated by Django 4.1.7 on 2023-04-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_sessie_school_alter_leerling_school_teamleider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leerling',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.school'),
        ),
    ]
