# Generated by Django 4.1.7 on 2023-05-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_alter_leerling_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('scholen', models.ManyToManyField(to='Login.school')),
            ],
        ),
        migrations.RenameField(
            model_name='begeleider',
            old_name='user',
            new_name='gebruiker',
        ),
        migrations.RenameField(
            model_name='begeleider',
            old_name='school',
            new_name='scholen',
        ),
        migrations.RenameField(
            model_name='teamleider',
            old_name='user',
            new_name='gebruiker',
        ),
        migrations.CreateModel(
            name='Vak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('niveaus', models.ManyToManyField(to='Login.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Materiaal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('bestand', models.FileField(upload_to='materialen/')),
                ('klas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.klas')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.niveau')),
                ('vak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.vak')),
            ],
        ),
        migrations.AddField(
            model_name='klas',
            name='niveaus',
            field=models.ManyToManyField(to='Login.niveau'),
        ),
        migrations.AddField(
            model_name='klas',
            name='vakken',
            field=models.ManyToManyField(to='Login.vak'),
        ),
        migrations.AddField(
            model_name='leerling',
            name='klas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.klas'),
        ),
    ]
