# Generated by Django 4.1.7 on 2023-05-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_klas_niveau_rename_user_begeleider_gebruiker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessie',
            name='vak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.vak'),
        ),
    ]
