# Generated by Django 4.1.7 on 2023-05-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_sessie_vak'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaal',
            name='omschrijving',
            field=models.TextField(default='nog te schrijven'),
        ),
        migrations.AlterField(
            model_name='begeleider',
            name='scholen',
            field=models.ManyToManyField(related_name='begeleiders', to='Login.school'),
        ),
        migrations.AlterField(
            model_name='klas',
            name='niveaus',
            field=models.ManyToManyField(related_name='klassen', to='Login.niveau'),
        ),
        migrations.AlterField(
            model_name='klas',
            name='vakken',
            field=models.ManyToManyField(related_name='klassen', to='Login.vak'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='scholen',
            field=models.ManyToManyField(related_name='niveaus', to='Login.school'),
        ),
        migrations.AlterField(
            model_name='sessie',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.school'),
        ),
        migrations.AlterField(
            model_name='vak',
            name='niveaus',
            field=models.ManyToManyField(related_name='vakken', to='Login.niveau'),
        ),
    ]
