# Generated by Django 4.1.7 on 2023-05-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_materiaal_omschrijving_alter_begeleider_scholen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leerling',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.niveau'),
        ),
    ]
