# Generated by Django 4.1.7 on 2023-05-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_leerling_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaal',
            name='omschrijving',
            field=models.TextField(default='Schrijf de beschrijvingen zo uitgebreid mogelijk. We gaan dit later verwerken in een zoeksysteem'),
        ),
        migrations.AlterField(
            model_name='sessie',
            name='begeleider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.begeleider'),
        ),
    ]
