# Generated by Django 4.2 on 2023-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_leerling_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaal',
            name='omschrijving',
            field=models.TextField(default='Schrijf de beschrijvingen zo uitgebreid mogelijk. We gaan dit later verwerken in een zoeksysteem'),
        ),
    ]
