# Generated by Django 4.1.7 on 2023-05-24 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0016_alter_materiaal_omschrijving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
