# Generated by Django 4.1.7 on 2023-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0017_alter_sessie_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
