# Generated by Django 4.1.7 on 2023-05-24 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0018_alter_sessie_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
