# Generated by Django 4.1.7 on 2023-10-22 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0021_leerling_gebruiker_leerlingvakrating_leerling_vakken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.date(2023, 10, 22)),
        ),
    ]
