# Generated by Django 4.1.7 on 2023-10-25 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0022_alter_sessie_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
        migrations.CreateModel(
            name='LeerlingVakRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijfer', models.IntegerField()),
                ('beschrijving', models.TextField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('leerling_vak_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.leerlingvakrating')),
            ],
        ),
    ]
