# Generated by Django 4.1.7 on 2023-10-28 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0023_alter_sessie_datum_leerlingvakratinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='secret_code',
            field=models.CharField(default='Frk1It', max_length=6),
        ),
        migrations.AlterField(
            model_name='leerlingvakratinghistory',
            name='cijfer',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.date(2023, 10, 28)),
        ),
    ]
