# Generated by Django 4.1.7 on 2023-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0024_school_secret_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='secret_code',
            field=models.CharField(default='AZqzAF', max_length=6),
        ),
    ]
