# Generated by Django 4.1.7 on 2023-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0026_alter_school_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='secret_code',
            field=models.CharField(default='f2AjB89', max_length=6),
        ),
    ]
