# Generated by Django 4.1.7 on 2023-11-08 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0027_alter_school_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
    ]
