# Generated by Django 4.1.7 on 2023-12-30 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0028_alter_sessie_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.date(2023, 12, 30)),
        ),
    ]
