# Generated by Django 4.1.7 on 2024-01-02 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0029_alter_sessie_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessie',
            name='datum',
            field=models.DateField(default=datetime.date(2024, 1, 2)),
        ),
    ]
