name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.IP }} >> ~/.ssh/known_hosts

    - name: SETUP SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        IP: ${{ secrets.IP }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub
        ssh-keyscan -H $IP >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        USER_IP: ${{ secrets.USER_IP }}
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER_IP <<EOF
        cd /var/www/new_site
        source env/bin/activate
        pip install -r requirements.txt
        git fetch origin
        git reset --hard origin/main
        git pull
        python manage.py collectstatic --noinput
        python manage.py makemigrations --merge
        yes
        python manage.py migrate
        sudo systemctl restart apache2
        EOF
